language: node_js
cache: npm

node_js:
  - 8
  - 10
  - 12

sudo: false

branches:
  only:
    - master
    - /^greenkeeper/.*$/

env:
  matrix:
    - SEQUELIZE_VERSION=4
    - SEQUELIZE_VERSION=5
    - SEQUELIZE_VERSION=6

  global:
    - TEST=1

matrix:
  fast_finish: true

  include:
    - node_js: 10
      env: TEST=0 LINT=1

    - node_js: 10
      env: TEST=0 COVERAGE=1

    - stage: deploy
      node_js: 10
      env: TEST=0 COVERAGE=0 LINT=0
      script:
        - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
        - git remote rm origin
        - git remote add origin https://alt3:${GITHUB_TOKEN}@github.com/alt3/sequelize-to-json-schemas.git
        - git symbolic-ref HEAD refs/heads/master
        - npm run release
      on:
        branch: master
      if: "branch = master AND type = push AND commit_message !~ /(?i:no-release)|^(?i:chore: release)/"

before_script:
 - sh -c "if [ '$TEST' = '1' ]; then npm install sequelize@^$SEQUELIZE_VERSION.0.0; fi"

script:
  - sh -c "if [ '$TEST' = '1' ]; then npm run test; fi"
  - sh -c "if [ '$LINT' = '1' ]; then npm run lint; fi"
  - sh -c "if [ '$COVERAGE' = '1' ]; then npm run coverage; fi"

after_success:
  - if [[ $COVERAGE == 1 ]]; then bash <(curl -s https://codecov.io/bash); fi

notifications:
  email:
    on_success: never
    on_failure: always
