sudo: false
language: node_js
matrix:
  include:
  - node_js: node # Current
    env: BUILD_DOCS=true REPORT_COVERAGE=true
  - node_js: --lts # LTS
    env: NPM_DEPLOY=true
  - node_js: 4 # Minimum required
script:
- npm test -- -- --timeout 10000
- '[[ "$BUILD_DOCS" != true ]] || npm run doc' # Ensures ESDoc generation doesn't fail
after_success:
- '[[ "$REPORT_COVERAGE" != true ]] || cat coverage/lcov.info | ./node_modules/.bin/codecov'
- '[[ "$REPORT_COVERAGE" != true ]] || cat coverage/lcov.info | ./node_modules/.bin/codeclimate-test-reporter'
deploy:
  provider: npm
  email: pro.alexandre.mercier@gmail.com
  api_key: $NPM_AUTH_TOKEN
  on:
    tags: true
    repo: amercier/npm-package-skeleton # Prevents publishing on PRs
    condition: $NPM_DEPLOY = true # Prevents publishing on each matrix build
cache:
  directories:
  - $HOME/.nvm
