language: node_js
matrix:
  include:
    - node_js: node # Current
      env: BUILD_DOCS=true REPORT_COVERAGE=true
    - node_js: --lts # LTS
      env: NPM_DEPLOY=true
    - node_js: 6 # Minimum required
install:
  - npm install --loglevel http # Prevent timeouts for inactivity
before_script:
  - npm run lint
script:
  - npm test -- --coverage
  - '[[ "$BUILD_DOCS" != true ]] || npm run doc' # Ensures ESDoc generation doesn't fail
  - '[[ "$REPORT_COVERAGE" != true ]] || codecov'
deploy:
  provider: npm
  email: pro.alexandre.mercier@gmail.com
  api_key: $NPM_AUTH_TOKEN
  on:
    tags: true
    repo: amercier/npm-package-skeleton # Prevents publishing on PRs
    condition: $NPM_DEPLOY = true # Prevents publishing on each matrix build
cache:
  directories:
    - $HOME/.npm
